Attribute VB_Name = "modNombresCA"
Option Compare Database
Option Explicit

Public Sub PoblarNombresCA()

    ' ==== NOMS CATALANS REALS (FREQÜENTS I PATRIMONIALS) ====

    ' --- Femenins freqüents ---
    AgregarEntradaDiccionario "CA", "MARTA", "MARTA", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "LAIA", "LAIA", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "JÚLIA", "JULIA", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "NÚRIA", "NURIA", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "CLARA", "CLARA", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "MARIA", "MARIA", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "ANNA", "ANNA", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "PAULA", "PAULA", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "SARA", "SARA", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "CARLA", "CARLA", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "ONA", "ONA", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "JANA", "JANA", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "MIREIA", "MIREIA", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "ARLET", "ARLET", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "JUDIT", "JUDIT", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "NOA", "NOA", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "IRIS", "IRIS", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "ABRIL", "ABRIL", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "XÈNIA", "XENIA", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "LLÚCIA", "LLUCIA", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "LLUNA", "LLUNA", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "CARME", "CARME", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "MONTSE", "MONTSE", "NOMBRE", "Hipocorístic", ""   ' De Montserrat

    ' --- Femenins patrimonials ---
    AgregarEntradaDiccionario "CA", "EVA", "EVA", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "HELENA", "HELENA", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "MERCÈ", "MERCE", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "AINA", "AINA", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "ELNA", "ELNA", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "CARLOTA", "CARLOTA", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "GISELA", "GISELA", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "IVET", "IVET", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "JORDINA", "JORDINA", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "LAURA", "LAURA", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "LEA", "LEA", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "MARGARIDA", "MARGARIDA", "NOMBRE", "Patrimonial", ""
    AgregarEntradaDiccionario "CA", "MARIONA", "MARIONA", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "MIQUELA", "MIQUELA", "NOMBRE", "Patrimonial", ""

    ' --- Masculins freqüents ---
    AgregarEntradaDiccionario "CA", "MARC", "MARC", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "ORIOL", "ORIOL", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "POL", "POL", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "GERARD", "GERARD", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "PAU", "PAU", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "JOAN", "JOAN", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "ARNAU", "ARNAU", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "JAN", "JAN", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "BIEL", "BIEL", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "ERIC", "ERIC", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "GUILLEM", "GUILLEM", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "ROGER", "ROGER", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "FERRAN", "FERRAN", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "LLUC", "LLUC", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "MIQUEL", "MIQUEL", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "XAVIER", "SHAVIER", "NOMBRE", "Patrimonial", ""
    AgregarEntradaDiccionario "CA", "XAVI", "SHAVI", "NOMBRE", "Hipocorístic", ""   ' De Xavier
    AgregarEntradaDiccionario "CA", "XIM", "SHIM", "NOMBRE", "Patrimonial", ""
    AgregarEntradaDiccionario "CA", "LLUÍS", "LLUÍS", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "NIL", "NIL", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "TEO", "TEO", "NOMBRE", "Frecuent", ""

    ' --- Masculins patrimonials ---
    AgregarEntradaDiccionario "CA", "ADRIÀ", "ADRIA", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "ALBERT", "ALBERT", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "ÀLEX", "ALEX", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "ARMAND", "ARMAND", "NOMBRE", "Patrimonial", ""
    AgregarEntradaDiccionario "CA", "BLAI", "BLAI", "NOMBRE", "Patrimonial", ""
    AgregarEntradaDiccionario "CA", "CARLES", "CARLES", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "DÍDAC", "DIDAC", "NOMBRE", "Patrimonial", ""
    AgregarEntradaDiccionario "CA", "ELIES", "ELIES", "NOMBRE", "Patrimonial", ""
    AgregarEntradaDiccionario "CA", "ENRIC", "ENRIC", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "EUDALD", "EUDALD", "NOMBRE", "Patrimonial", ""
    AgregarEntradaDiccionario "CA", "GENÍS", "GENIS", "NOMBRE", "Patrimonial", ""
    AgregarEntradaDiccionario "CA", "IGNASI", "IGNASI", "NOMBRE", "Patrimonial", ""
    AgregarEntradaDiccionario "CA", "ISIDRE", "ISIDRE", "NOMBRE", "Patrimonial", ""
    AgregarEntradaDiccionario "CA", "JORDI", "JORDI", "NOMBRE", "Frecuent", ""
    AgregarEntradaDiccionario "CA", "JOFRE", "JOFRE", "NOMBRE", "Patrimonial", ""
    AgregarEntradaDiccionario "CA", "MARCEL", "MARCEL", "NOMBRE", "Patrimonial", ""

    ' --- Noms patrimonials afegits per completitud ---
    AgregarEntradaDiccionario "CA", "MARIÀ", "MARIA", "NOMBRE", "Patrimonial", ""   ' Masculí, equivalent a Mariano
    AgregarEntradaDiccionario "CA", "BOI", "BOI", "NOMBRE", "Patrimonial", ""       ' Equivalent a Baudili
    AgregarEntradaDiccionario "CA", "CUGAT", "CUGAT", "NOMBRE", "Patrimonial", ""   ' Equivalent a Cucufat

    ' ==== HIPOCORES CATALANS VÀLIDS ====
    AgregarEntradaDiccionario "CA", "TONI", "TONI", "NOMBRE", "Hipocorístic", ""    ' De Antoni
    AgregarEntradaDiccionario "CA", "QUIM", "QUIM", "NOMBRE", "Hipocorístic", ""    ' De Joaquim
    AgregarEntradaDiccionario "CA", "PEP", "PEP", "NOMBRE", "Hipocorístic", ""      ' De Josep
    AgregarEntradaDiccionario "CA", "CESC", "CESC", "NOMBRE", "Hipocorístic", ""    ' De Francesc
    AgregarEntradaDiccionario "CA", "TXELL", "TXELL", "NOMBRE", "Hipocorístic", ""  ' De Meritxell
    
    ' ==== BLOQUE 3–4: noms nous (sense duplicats) ====

' --- Femenins ---
AgregarEntradaDiccionario "CA", "NORA", "NORA", "NOMBRE", "Frecuent", ""
AgregarEntradaDiccionario "CA", "OLIVIA", "OLIVIA", "NOMBRE", "Frecuent", ""
AgregarEntradaDiccionario "CA", "RAQUEL", "RAQUEL", "NOMBRE", "Frecuent", ""
AgregarEntradaDiccionario "CA", "REBECA", "REBECA", "NOMBRE", "Frecuent", ""
AgregarEntradaDiccionario "CA", "ROSA", "ROSA", "NOMBRE", "Frecuent", ""
AgregarEntradaDiccionario "CA", "SANDRA", "SANDRA", "NOMBRE", "Frecuent", ""
AgregarEntradaDiccionario "CA", "SÍLVIA", "SILVIA", "NOMBRE", "Frecuent", ""
AgregarEntradaDiccionario "CA", "TÀNIA", "TANIA", "NOMBRE", "Frecuent", ""
AgregarEntradaDiccionario "CA", "TURA", "TURA", "NOMBRE", "Patrimonial", ""
AgregarEntradaDiccionario "CA", "VALÈRIA", "VALERIA", "NOMBRE", "Frecuent", ""
AgregarEntradaDiccionario "CA", "GINESTA", "GINESTA", "NOMBRE", "Patrimonial", ""

' --- Masculins ---
AgregarEntradaDiccionario "CA", "ADAM", "ADAM", "NOMBRE", "Frecuent", ""
AgregarEntradaDiccionario "CA", "ALFONS", "ALFONS", "NOMBRE", "Patrimonial", ""
AgregarEntradaDiccionario "CA", "AMAT", "AMAT", "NOMBRE", "Patrimonial", ""
AgregarEntradaDiccionario "CA", "ANDREU", "ANDREU", "NOMBRE", "Frecuent", ""
AgregarEntradaDiccionario "CA", "ANTONI", "ANTONI", "NOMBRE", "Frecuent", ""
AgregarEntradaDiccionario "CA", "ARTUR", "ARTUR", "NOMBRE", "Frecuent", ""
AgregarEntradaDiccionario "CA", "AURELI", "AURELI", "NOMBRE", "Patrimonial", ""
AgregarEntradaDiccionario "CA", "BARTOMEU", "BARTOMEU", "NOMBRE", "Patrimonial", ""
AgregarEntradaDiccionario "CA", "BERNAT", "BERNAT", "NOMBRE", "Patrimonial", ""
AgregarEntradaDiccionario "CA", "BONAVENTURA", "BONAVENTURA", "NOMBRE", "Patrimonial", ""
AgregarEntradaDiccionario "CA", "CINTO", "CINTO", "NOMBRE", "Hipocorístic", ""   ' De Jacint
AgregarEntradaDiccionario "CA", "CONRAD", "CONRAD", "NOMBRE", "Patrimonial", ""
AgregarEntradaDiccionario "CA", "DAMIÀ", "DAMIA", "NOMBRE", "Patrimonial", ""
AgregarEntradaDiccionario "CA", "DANIEL", "DANIEL", "NOMBRE", "Frecuent", ""
AgregarEntradaDiccionario "CA", "DAVID", "DAVID", "NOMBRE", "Frecuent", ""
AgregarEntradaDiccionario "CA", "EDUARD", "EDUARD", "NOMBRE", "Frecuent", ""
AgregarEntradaDiccionario "CA", "EMILI", "EMILI", "NOMBRE", "Patrimonial", ""
AgregarEntradaDiccionario "CA", "ERNEST", "ERNEST", "NOMBRE", "Patrimonial", ""
AgregarEntradaDiccionario "CA", "ESTEVE", "ESTEVE", "NOMBRE", "Patrimonial", ""
AgregarEntradaDiccionario "CA", "EULOGI", "EULOGI", "NOMBRE", "Patrimonial", ""
AgregarEntradaDiccionario "CA", "FABIÀ", "FABIA", "NOMBRE", "Patrimonial", ""
AgregarEntradaDiccionario "CA", "FELIU", "FELIU", "NOMBRE", "Patrimonial", ""
AgregarEntradaDiccionario "CA", "FERRIOL", "FERRIOL", "NOMBRE", "Patrimonial", ""
AgregarEntradaDiccionario "CA", "FREDERIC", "FREDERIC", "NOMBRE", "Patrimonial", ""
AgregarEntradaDiccionario "CA", "GABRIEL", "GABRIEL", "NOMBRE", "Frecuent", ""
AgregarEntradaDiccionario "CA", "GAEL", "GAEL", "NOMBRE", "Frecuent", ""
AgregarEntradaDiccionario "CA", "GERMÀ", "GERMAN", "NOMBRE", "Patrimonial", ""
AgregarEntradaDiccionario "CA", "GRAU", "GRAU", "NOMBRE", "Patrimonial", ""
AgregarEntradaDiccionario "CA", "GUIU", "GUIU", "NOMBRE", "Patrimonial", ""
AgregarEntradaDiccionario "CA", "HUG", "HUG", "NOMBRE", "Patrimonial", ""
AgregarEntradaDiccionario "CA", "ILDEFONS", "ILDEFONS", "NOMBRE", "Patrimonial", ""
AgregarEntradaDiccionario "CA", "ISMAEL", "ISMAEL", "NOMBRE", "Frecuent", ""
AgregarEntradaDiccionario "CA", "JAUME", "JAUME", "NOMBRE", "Patrimonial", ""
AgregarEntradaDiccionario "CA", "JOSEP", "JOSEP", "NOMBRE", "Frecuent", ""
AgregarEntradaDiccionario "CA", "LLORENÇ", "LLORENC", "NOMBRE", "Patrimonial", ""
AgregarEntradaDiccionario "CA", "LLUCIÀ", "LLUCIÀ", "NOMBRE", "Patrimonial", ""
AgregarEntradaDiccionario "CA", "MANEL", "MANEL", "NOMBRE", "Frecuent", ""
AgregarEntradaDiccionario "CA", "MARÇAL", "MARCAL", "NOMBRE", "Patrimonial", ""
AgregarEntradaDiccionario "CA", "MATEU", "MATEU", "NOMBRE", "Patrimonial", ""
AgregarEntradaDiccionario "CA", "MAURI", "MAURI", "NOMBRE", "Patrimonial", ""
AgregarEntradaDiccionario "CA", "MOISÈS", "MOISES", "NOMBRE", "Patrimonial", ""
AgregarEntradaDiccionario "CA", "NARCÍS", "NARCIS", "NOMBRE", "Patrimonial", ""
AgregarEntradaDiccionario "CA", "NÈSTOR", "NESTOR", "NOMBRE", "Frecuent", ""
AgregarEntradaDiccionario "CA", "NOEL", "NOEL", "NOMBRE", "Frecuent", ""
AgregarEntradaDiccionario "CA", "OLIVER", "OLIVER", "NOMBRE", "Frecuent", ""
AgregarEntradaDiccionario "CA", "ÒSCAR", "OSCAR", "NOMBRE", "Frecuent", ""
AgregarEntradaDiccionario "CA", "OT", "OT", "NOMBRE", "Patrimonial", ""
AgregarEntradaDiccionario "CA", "PERE", "PERE", "NOMBRE", "Patrimonial", ""
AgregarEntradaDiccionario "CA", "RAFAEL", "RAFAEL", "NOMBRE", "Frecuent", ""
AgregarEntradaDiccionario "CA", "RAIMON", "RAIMON", "NOMBRE", "Patrimonial", ""
AgregarEntradaDiccionario "CA", "RAMON", "RAMON", "NOMBRE", "Patrimonial", ""
AgregarEntradaDiccionario "CA", "RICARD", "RICARD", "NOMBRE", "Patrimonial", ""
AgregarEntradaDiccionario "CA", "SERGI", "SERGI", "NOMBRE", "Frecuent", ""
AgregarEntradaDiccionario "CA", "SIMÓ", "SIMO", "NOMBRE", "Patrimonial", ""
AgregarEntradaDiccionario "CA", "TOMÀS", "TOMAS", "NOMBRE", "Patrimonial", ""

AgregarEntradaDiccionario "CA", "DÍDAC", "DIDAC", "NOMBRE", "Patrimonial", ""    ' Equivalent a Diego



'Public Sub CargarDiccionarioCA()
'
'
'    ' ==== BLOQUE 3: noms 101–150 ====
'
'    AgregarEntradaDiccionario "CA", "NORA", "NORA", "NOMBRE", "Frecuent", "['no??]"
'    AgregarEntradaDiccionario "CA", "OLIVIA", "OLIVIA", "NOMBRE", "Frecuent", "[u'lißi?]"
'    AgregarEntradaDiccionario "CA", "RAQUEL", "RAQUEL", "NOMBRE", "Frecuent", "[r?'k?l]"
'    AgregarEntradaDiccionario "CA", "REBECA", "REBECA", "NOMBRE", "Frecuent", "[r?'ß?k?]"
'    AgregarEntradaDiccionario "CA", "ROSA", "ROSA", "NOMBRE", "Frecuent", "['roz?]"
'    AgregarEntradaDiccionario "CA", "SANDRA", "SANDRA", "NOMBRE", "Frecuent", "['sand??]"
'    AgregarEntradaDiccionario "CA", "SILVIA", "SILVIA", "NOMBRE", "Frecuent", "['silßi?]"
'    AgregarEntradaDiccionario "CA", "TANIA", "TANIA", "NOMBRE", "Frecuent", "['tani?]"
'    AgregarEntradaDiccionario "CA", "TURA", "TURA", "NOMBRE", "Frecuent", "['tu??]"
'    AgregarEntradaDiccionario "CA", "VALERIA", "VALERIA", "NOMBRE", "Frecuent", "[b?'le?i?]"
'
'    AgregarEntradaDiccionario "CA", "ADAM", "ADAM", "NOMBRE", "Frecuent", "[?'ðan]"
'    AgregarEntradaDiccionario "CA", "ALFONS", "ALFONS", "NOMBRE", "Frecuent", "[?l'fons]"
'    AgregarEntradaDiccionario "CA", "AMAT", "AMAT", "NOMBRE", "Frecuent", "[?'mat]"
'    AgregarEntradaDiccionario "CA", "ANDREU", "ANDREU", "NOMBRE", "Frecuent", "[?n'd?ew]"
'    AgregarEntradaDiccionario "CA", "ANTONI", "ANTONI", "NOMBRE", "Frecuent", "[?n'toni]"
'    AgregarEntradaDiccionario "CA", "ARISTIDE", "ARISTIDE", "NOMBRE", "Frecuent", "[?'?istið?]"
'    AgregarEntradaDiccionario "CA", "ARTUR", "ARTUR", "NOMBRE", "Frecuent", "[??'tu?]"
'    AgregarEntradaDiccionario "CA", "AURELI", "AURELI", "NOMBRE", "Frecuent", "[aw'?eli]"
'    AgregarEntradaDiccionario "CA", "BARTOMEU", "BARTOMEU", "NOMBRE", "Frecuent", "[b??tu'mew]"
'    AgregarEntradaDiccionario "CA", "BERNAT", "BERNAT", "NOMBRE", "Frecuent", "[b??'nat]"
'
'    AgregarEntradaDiccionario "CA", "BLAS", "BLAS", "NOMBRE", "Frecuent", "['blas]"
'    AgregarEntradaDiccionario "CA", "BONAVENTURA", "BONAVENTURA", "NOMBRE", "Frecuent", "[bun?ß?n'tu??]"
'    AgregarEntradaDiccionario "CA", "CESC", "CESC", "NOMBRE", "Frecuent", "['s?sk]"
'    AgregarEntradaDiccionario "CA", "CINTO", "CINTO", "NOMBRE", "Frecuent", "['sinto]"
'    AgregarEntradaDiccionario "CA", "CONRAD", "CONRAD", "NOMBRE", "Frecuent", "[kun'?at]"
'    AgregarEntradaDiccionario "CA", "DAMIÀ", "DAMIA", "NOMBRE", "Frecuent", "[d?'mja]"
'    AgregarEntradaDiccionario "CA", "DANIEL", "DANIEL", "NOMBRE", "Frecuent", "[d?'ni?l]"
'    AgregarEntradaDiccionario "CA", "DARIUS", "DARIUS", "NOMBRE", "Frecuent", "[d?'?iwz]"
'    AgregarEntradaDiccionario "CA", "DAVID", "DAVID", "NOMBRE", "Frecuent", "[d?'ßit]"
'    AgregarEntradaDiccionario "CA", "DIDIER", "DIDIER", "NOMBRE", "Frecuent", "[di'dje]"
'
'    AgregarEntradaDiccionario "CA", "EDUARD", "EDUARD", "NOMBRE", "Frecuent", "[?ðu'a?t]"
'    AgregarEntradaDiccionario "CA", "EMILI", "EMILI", "NOMBRE", "Frecuent", "[?'mili]"
'    AgregarEntradaDiccionario "CA", "ERNEST", "ERNEST", "NOMBRE", "Frecuent", "[??'nest]"
'    AgregarEntradaDiccionario "CA", "ESTEVE", "ESTEVE", "NOMBRE", "Frecuent", "[?s'teß?]"
'    AgregarEntradaDiccionario "CA", "EUDALD", "EUDALD", "NOMBRE", "Frecuent", "[ew'ðalt]"
'    AgregarEntradaDiccionario "CA", "EULOGI", "EULOGI", "NOMBRE", "Frecuent", "[ew'lo?i]"
'    AgregarEntradaDiccionario "CA", "FABIÀ", "FABIA", "NOMBRE", "Frecuent", "[f?'ßja]"
'    AgregarEntradaDiccionario "CA", "FELIU", "FELIU", "NOMBRE", "Frecuent", "[f?'liw]"
'    AgregarEntradaDiccionario "CA", "FERRIOL", "FERRIOL", "NOMBRE", "Frecuent", "[f?'?j?l]"
'    AgregarEntradaDiccionario "CA", "FREDERIC", "FREDERIC", "NOMBRE", "Frecuent", "[f??d?'?ik]"
'
'    AgregarEntradaDiccionario "CA", "GABRIEL", "GABRIEL", "NOMBRE", "Frecuent", "[g?ß?i'?l]"
'    AgregarEntradaDiccionario "CA", "GAEL", "GAEL", "NOMBRE", "Frecuent", "[ga'?l]"
'    AgregarEntradaDiccionario "CA", "GENÍS", "GENIS", "NOMBRE", "Frecuent", "[??'nis]"
'    AgregarEntradaDiccionario "CA", "GERMAN", "GERMAN", "NOMBRE", "Frecuent", "[???'man]"
'    AgregarEntradaDiccionario "CA", "GINESTA", "GINESTA", "NOMBRE", "Frecuent", "[?i'nest?]"
'    AgregarEntradaDiccionario "CA", "GISELA", "GISELA", "NOMBRE", "Frecuent", "[?i'z?l?]"
'    AgregarEntradaDiccionario "CA", "GRAU", "GRAU", "NOMBRE", "Frecuent", "['g?aw]"
'    AgregarEntradaDiccionario "CA", "GUIU", "GUIU", "NOMBRE", "Frecuent", "['giw]"
'    AgregarEntradaDiccionario "CA", "GUILLEM", "GUILLEM", "NOMBRE", "Frecuent", "[gi'??m]"
'    AgregarEntradaDiccionario "CA", "GURMET", "GURMET", "NOMBRE", "Frecuent", "[gu?'m?t]"
'
'    ' ==== BLOQUE 4: noms 151–200 ====
'
'    AgregarEntradaDiccionario "CA", "GUILLAUME", "GUILLAUME", "NOMBRE", "Frecuent", "[gi'?om]"
'    AgregarEntradaDiccionario "CA", "HUG", "HUG", "NOMBRE", "Frecuent", "['uk]"
'    AgregarEntradaDiccionario "CA", "ILDEFONS", "ILDEFONS", "NOMBRE", "Frecuent", "[ild?'fons]"
'    AgregarEntradaDiccionario "CA", "ISMAEL", "ISMAEL", "NOMBRE", "Frecuent", "[izma'?l]"
'    AgregarEntradaDiccionario "CA", "JAUME", "JAUME", "NOMBRE", "Frecuent", "['?awm?]"
'    AgregarEntradaDiccionario "CA", "JOSEP", "JOSEP", "NOMBRE", "Frecuent", "[?u'z?p]"
'    AgregarEntradaDiccionario "CA", "LLORENÇ", "LLORENC", "NOMBRE", "Frecuent", "[?u'??ns]"
'    AgregarEntradaDiccionario "CA", "LLUCIÀ", "LLUCIÀ", "NOMBRE", "Frecuent", "[?usi'a]"
'    AgregarEntradaDiccionario "CA", "LLUÍS", "LLUÍS", "NOMBRE", "Frecuent", "[?u'is]"
'    AgregarEntradaDiccionario "CA", "MANEL", "MANEL", "NOMBRE", "Frecuent", "[m?'n?l]"
'
'    AgregarEntradaDiccionario "CA", "MARÇAL", "MARCAL", "NOMBRE", "Frecuent", "[m??'sal]"
'    AgregarEntradaDiccionario "CA", "MARCOS", "MARCOS", "NOMBRE", "Frecuent", "['ma?kus]"
'    AgregarEntradaDiccionario "CA", "MARIÀ", "MARIA", "NOMBRE", "Frecuent", "[m??i'a]"
'    AgregarEntradaDiccionario "CA", "MATEU", "MATEU", "NOMBRE", "Frecuent", "[m?'tew]"
'    AgregarEntradaDiccionario "CA", "MAURI", "MAURI", "NOMBRE", "Frecuent", "['maw?i]"
'    AgregarEntradaDiccionario "CA", "MIQUEL", "MIQUEL", "NOMBRE", "Frecuent", "[mi'k?l]"
'    AgregarEntradaDiccionario "CA", "MOISÈS", "MOISES", "NOMBRE", "Frecuent", "[muj'z?s]"
'    AgregarEntradaDiccionario "CA", "NARCÍS", "NARCIS", "NOMBRE", "Frecuent", "[n??'sis]"
'    AgregarEntradaDiccionario "CA", "NESTOR", "NESTOR", "NOMBRE", "Frecuent", "['nestu?]"
'    AgregarEntradaDiccionario "CA", "NIL", "NIL", "NOMBRE", "Frecuent", "['nil]"
'
'    AgregarEntradaDiccionario "CA", "NOEL", "NOEL", "NOMBRE", "Frecuent", "[nu'?l]"
'    AgregarEntradaDiccionario "CA", "NÚRIA", "NURIA", "NOMBRE", "Frecuent", "['nu?i?]"
'    AgregarEntradaDiccionario "CA", "OLIVER", "OLIVER", "NOMBRE", "Frecuent", "[u'liße]"
'    AgregarEntradaDiccionario "CA", "OSCAR", "OSCAR", "NOMBRE", "Frecuent", "['osk??]"
'    AgregarEntradaDiccionario "CA", "OT", "OT", "NOMBRE", "Frecuent", "['ot]"
'    AgregarEntradaDiccionario "CA", "PERE", "PERE", "NOMBRE", "Frecuent", "['pe??]"
'    AgregarEntradaDiccionario "CA", "POL", "POL", "NOMBRE", "Frecuent", "['p?l]"
'    AgregarEntradaDiccionario "CA", "RAFAEL", "RAFAEL", "NOMBRE", "Frecuent", "[r?f?'?l]"
'    AgregarEntradaDiccionario "CA", "RAIMON", "RAIMON", "NOMBRE", "Frecuent", "[r?j'mon]"
'    AgregarEntradaDiccionario "CA", "RAMON", "RAMON", "NOMBRE", "Frecuent", "[r?'mon]"
'
'    AgregarEntradaDiccionario "CA", "RICARD", "RICARD", "NOMBRE", "Frecuent", "[ri'ka?t]"
'    AgregarEntradaDiccionario "CA", "ROGER", "ROGER", "NOMBRE", "Frecuent", "[ru'?e]"
'    AgregarEntradaDiccionario "CA", "ROVIRA", "ROVIRA", "NOMBRE", "Frecuent", "[ru'ßi??]"
'    AgregarEntradaDiccionario "CA", "SANTI", "SANTI", "NOMBRE", "Frecuent", "['santi]"
'    AgregarEntradaDiccionario "CA", "SEBASTIÀ", "SEBASTIA", "NOMBRE", "Frecuent", "[s?b?s'tja]"
'    AgregarEntradaDiccionario "CA", "SERGI", "SERGI", "NOMBRE", "Frecuent", "['s???i]"
'    AgregarEntradaDiccionario "CA", "SIMÓ", "SIMO", "NOMBRE", "Frecuent", "[si'mo]"
'    AgregarEntradaDiccionario "CA", "TOMÀS", "TOMAS", "NOMBRE", "Frecuent", "[tu'mas]"
'    AgregarEntradaDiccionario "CA", "TONI", "TONI", "NOMBRE", "Frecuent", "['toni]"
'    AgregarEntradaDiccionario "CA", "XAVIER", "SHAVIER", "NOMBRE", "Patrimonial", "[??'ßi.e]"
'
'    AgregarEntradaDiccionario "CA", "XAVI", "SHAVI", "NOMBRE", "Patrimonial", "['?aßi]"
'    AgregarEntradaDiccionario "CA", "XIM", "SHIM", "NOMBRE", "Patrimonial", "['?im]"
'    AgregarEntradaDiccionario "CA", "XIRGU", "SHIRGU", "NOMBRE", "Patrimonial", "['?i??u]"
'    AgregarEntradaDiccionario "CA", "XÈNIA", "SHENIA", "NOMBRE", "Patrimonial", "['??ni?]"
'    AgregarEntradaDiccionario "CA", "XESC", "SHESC", "NOMBRE", "Patrimonial", "['??sk]"
'    AgregarEntradaDiccionario "CA", "XAVIERA", "SHAVIERA", "NOMBRE", "Patrimonial", "[??ßi'e??]"
'    AgregarEntradaDiccionario "CA", "XERARDA", "SHERARDA", "NOMBRE", "Patrimonial", "[??'?a?ð?]"
'    AgregarEntradaDiccionario "CA", "XURIGUERA", "SHURIGUERA", "NOMBRE", "Patrimonial", "[?u?i'?e??]"
'    AgregarEntradaDiccionario "CA", "XURXO", "SHURSHO", "NOMBRE", "Adaptació gallega", "['?u??o]"
'    AgregarEntradaDiccionario "CA", "XILENA", "SHILENA", "NOMBRE", "Cultisme", "[?i'len?]"

    Debug.Print "Fin"
End Sub

Public Sub PoblarApellidosCA()

' ==== BLOQUE 1 — APELLIDOS CATALANES 1–50 ====

AgregarEntradaDiccionario "CA", "SOLER", "SOLER", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "SERRA", "SERRA", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VILA", "VILA", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "RIERA", "RIERA", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "PONS", "PONS", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "MAS", "MAS", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "FERRER", "FERRER", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VIDAL", "VIDAL", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "ROCA", "ROCA", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "ROVIRA", "ROVIRA", "APELLIDO", "Catalán", ""

AgregarEntradaDiccionario "CA", "SALVAT", "SALVAT", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "SALVÀ", "SALVA", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "RIPOLL", "RIPOLL", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "PUIG", "PUCH", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "PUJOL", "PUYOL", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "MIRÓ", "MIRO", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "FUSTER", "FUSTER", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VIVES", "VIVES", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "GUAL", "GUAL", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "GUIMERÀ", "GUIMERA", "APELLIDO", "Catalán", ""

AgregarEntradaDiccionario "CA", "FERRAN", "FERRAN", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "BERENGUER", "BERENGUER", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "MARCH", "MARCH", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "LLULL", "LLULL", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "LLORACH", "LLORAK", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "LLORÉNS", "LLORENS", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "LLORCA", "LLORCA", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "LLORÓ", "LLORO", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "LLORÀ", "LLORA", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "LLORIS", "LLORIS", "APELLIDO", "Catalán", ""

AgregarEntradaDiccionario "CA", "VALLS", "VALLS", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VALLÈS", "VALLES", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VALLMAJOR", "VALLMAJOR", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VALLHONRAT", "VALLHONRAT", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VALLDEORIOLA", "VALLDEORIOLA", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VALLDEBONA", "VALLDEBONA", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VALLDEPLANA", "VALLDEPLANA", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VALLDECABRES", "VALLDECABRES", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VALLDEPERAS", "VALLDEPERAS", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VALLDEBERT", "VALLDEBERT", "APELLIDO", "Catalán", ""

AgregarEntradaDiccionario "CA", "TORRENT", "TORRENT", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "TORRENTÓ", "TORRENTO", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "TORRAS", "TORRAS", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "TORRENTELL", "TORRENTELL", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "TORRENTATS", "TORRENTATS", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "TORRENTAL", "TORRENTAL", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "TORRENTELLÓ", "TORRENTELLO", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "TORRENTÍ", "TORRENTI", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "ROSELL", "ROSELL", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "SANTACANA", "SANTACANA", "APELLIDO", "Catalán", ""

' ==== BLOQUE 2 — APELLIDOS CATALANES 51–100 — DEFINITIVO ====

AgregarEntradaDiccionario "CA", "BARCELÓ", "BARCELO", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "MASCARÓ", "MASCARO", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "MIRALLES", "MIRALLES", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "RIBAS", "RIBAS", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "RIBES", "RIBES", "APELLIDO", "Catalán", ""

AgregarEntradaDiccionario "CA", "FARRÉ", "FARRE", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "FARRÉS", "FARRES", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "FARRIOL", "FARRIOL", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "FARRIOLS", "FARRIOLS", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "FARRIOLA", "FARRIOLA", "APELLIDO", "Catalán", ""

AgregarEntradaDiccionario "CA", "CASAS", "CASAS", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "CASELLAS", "CASELLAS", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "CASELLER", "CASELLER", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "CASELLERS", "CASELLERS", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "CASELLERA", "CASELLERA", "APELLIDO", "Catalán", ""

AgregarEntradaDiccionario "CA", "FABRA", "FABRA", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "FABREGAT", "FABREGAT", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "FABREGUES", "FABREGUES", "APELLIDO", "Catalán", ""

AgregarEntradaDiccionario "CA", "SEGARRA", "SEGARRA", "APELLIDO", "Catalán", ""

AgregarEntradaDiccionario "CA", "TARRÉS", "TARRES", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "TARRADELL", "TARRADELL", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "TARRADELLAS", "TARRADELLAS", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "TARRAGÓ", "TARRAGO", "APELLIDO", "Catalán", ""

AgregarEntradaDiccionario "CA", "VENDRELL", "VENDRELL", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VENDRELLS", "VENDRELLS", "APELLIDO", "Catalán", ""

AgregarEntradaDiccionario "CA", "ALCOVER", "ALCOVER", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "BENNÀSSAR", "BENNASSAR", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "ESTELRICH", "ESTELRRIK", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "MORAGUES", "MORAGUES", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "CANYELLES", "CANYELLES", "APELLIDO", "Catalán", ""

' ==== BLOQUE 3 — APELLIDOS CATALANES 101–150 ====

AgregarEntradaDiccionario "CA", "ROIG", "ROICH", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "ROIGÉ", "ROICHE", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "ROIGER", "ROICHER", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "ROIGET", "ROICHET", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "ROIGÓ", "ROICHO", "APELLIDO", "Catalán", ""

AgregarEntradaDiccionario "CA", "SOLDEVILA", "SOLDEVILA", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "SOLDEVILAR", "SOLDEVILAR", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "SOLDEVILERS", "SOLDEVILERS", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "SOLDEVILÓ", "SOLDEVILO", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "SOLDEVILAT", "SOLDEVILAT", "APELLIDO", "Catalán", ""

AgregarEntradaDiccionario "CA", "SAGRERA", "SAGRERA", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "SAGRERAS", "SAGRERAS", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "SAGRERÓ", "SAGRERO", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "SAGRERET", "SAGRERET", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "SAGRERELL", "SAGRERELL", "APELLIDO", "Catalán", ""

AgregarEntradaDiccionario "CA", "SURET", "SURET", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "SURETA", "SURETA", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "SURETÓ", "SURETO", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "SURETAS", "SURETAS", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "SURETET", "SURETET", "APELLIDO", "Catalán", ""

AgregarEntradaDiccionario "CA", "VILAR", "VILAR", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VILARÓ", "VILARO", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VILARDELL", "VILARDELL", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VILARDELLS", "VILARDELLS", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VILARDELLÓ", "VILARDELLO", "APELLIDO", "Catalán", ""

AgregarEntradaDiccionario "CA", "VILANOVA", "VILANOVA", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VILANOVES", "VILANOVES", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VILANOVELL", "VILANOVELL", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VILANOVELLÓ", "VILANOVELLO", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VILANOVERA", "VILANOVERA", "APELLIDO", "Catalán", ""

AgregarEntradaDiccionario "CA", "VILAPLANA", "VILAPLANA", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VILAPLANS", "VILAPLANS", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VILAPLANELL", "VILAPLANELL", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VILAPLANER", "VILAPLANER", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VILAPLANERA", "VILAPLANERA", "APELLIDO", "Catalán", ""

AgregarEntradaDiccionario "CA", "VILASECA", "VILASECA", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VILASECANS", "VILASECANS", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VILASECANA", "VILASECANA", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VILASECÓ", "VILASECO", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VILASEQUER", "VILASEQUER", "APELLIDO", "Catalán", ""

' ==== BLOQUE 3 — APELLIDOS CATALANES 101–150 ====

AgregarEntradaDiccionario "CA", "ROIG", "ROICH", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "ROIGÉ", "ROICHE", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "ROIGER", "ROICHER", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "ROIGET", "ROICHET", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "ROIGÓ", "ROICHO", "APELLIDO", "Catalán", ""

AgregarEntradaDiccionario "CA", "SOLDEVILA", "SOLDEVILA", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "SOLDEVILAR", "SOLDEVILAR", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "SOLDEVILERS", "SOLDEVILERS", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "SOLDEVILÓ", "SOLDEVILO", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "SOLDEVILAT", "SOLDEVILAT", "APELLIDO", "Catalán", ""

AgregarEntradaDiccionario "CA", "SAGRERA", "SAGRERA", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "SAGRERAS", "SAGRERAS", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "SAGRERÓ", "SAGRERO", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "SAGRERET", "SAGRERET", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "SAGRERELL", "SAGRERELL", "APELLIDO", "Catalán", ""

AgregarEntradaDiccionario "CA", "SURET", "SURET", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "SURETA", "SURETA", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "SURETÓ", "SURETO", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "SURETAS", "SURETAS", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "SURETET", "SURETET", "APELLIDO", "Catalán", ""

AgregarEntradaDiccionario "CA", "VILAR", "VILAR", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VILARÓ", "VILARO", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VILARDELL", "VILARDELL", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VILARDELLS", "VILARDELLS", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VILARDELLÓ", "VILARDELLO", "APELLIDO", "Catalán", ""

AgregarEntradaDiccionario "CA", "VILANOVA", "VILANOVA", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VILANOVES", "VILANOVES", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VILANOVELL", "VILANOVELL", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VILANOVELLÓ", "VILANOVELLO", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VILANOVERA", "VILANOVERA", "APELLIDO", "Catalán", ""

AgregarEntradaDiccionario "CA", "VILAPLANA", "VILAPLANA", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VILAPLANS", "VILAPLANS", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VILAPLANELL", "VILAPLANELL", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VILAPLANER", "VILAPLANER", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VILAPLANERA", "VILAPLANERA", "APELLIDO", "Catalán", ""

AgregarEntradaDiccionario "CA", "VILASECA", "VILASECA", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VILASECANS", "VILASECANS", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VILASECANA", "VILASECANA", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VILASECÓ", "VILASECO", "APELLIDO", "Catalán", ""
AgregarEntradaDiccionario "CA", "VILASEQUER", "VILASEQUER", "APELLIDO", "Catalán", ""

Debug.Print "Fin"

End Sub



'Public Sub PoblarApellidosCA_old()
'
'' ==== BLOQUE 1 — APELLIDOS CATALANES 1–50 ====
'
'AgregarEntradaDiccionario "CA", "PUIG", "PUCH", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "PUJOL", "PUJOL", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "VILA", "VILA", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "SOLER", "SOLER", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "SERRA", "SERRA", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "RIERA", "RIERA", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "FERRER", "FERRER", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "ROVIRA", "ROVIRA", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "BOSCH", "BOSK", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "VIDAL", "VIDAL", "APELLIDO", "Catalán", ""
'
'AgregarEntradaDiccionario "CA", "LLORET", "LLORET", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "CASALS", "CASALS", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "PRATS", "PRATS", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "FONT", "FONT", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "MAS", "MAS", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "GRAU", "GRAU", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "MARTÍ", "MARTI", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "LLORENS", "LLORENS", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "BALAGUER", "BALAGUER", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "MIRÓ", "MIRO", "APELLIDO", "Catalán", ""
'
'AgregarEntradaDiccionario "CA", "LLORACH", "LLORAK", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "ANYÓ", "AÑO", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "GUIMERÀ", "GUIMERA", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "GUAL", "GUAL", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "GUIXÀ", "GISHA", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "GUIX", "GISH", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "XAVIER", "SHAVIER", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "XURIGUERA", "SHURIGUERA", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "XICOT", "SHICOT", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "XARRIÉ", "SHARRIE", "APELLIDO", "Catalán", ""
'
'AgregarEntradaDiccionario "CA", "VALLS", "VALLS", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "VALLVERDÚ", "VALLVERDU", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "VALLMAJOR", "VALLMAJOR", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "VALLHONRAT", "VALLHONRAT", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "VALLÈS", "VALLES", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "VALLDECABRES", "VALLDECABRES", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "VALLDEPERAS", "VALLDEPERAS", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "VALLDEORIOLA", "VALLDEORIOLA", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "VALLDEPLANA", "VALLDEPLANA", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "VALLDEBONA", "VALLDEBONA", "APELLIDO", "Catalán", ""
'
'AgregarEntradaDiccionario "CA", "TORRENT", "TORRENT", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "TORRENTÓ", "TORRENTO", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "TORRENTÍ", "TORRENTI", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "TORRENTELL", "TORRENTELL", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "TORRENTERA", "TORRENTERA", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "TORRENTAL", "TORRENTAL", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "TORRENTALS", "TORRENTALS", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "TORRENTADA", "TORRENTADA", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "TORRENTATS", "TORRENTATS", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "TORRENTELLÓ", "TORRENTELLO", "APELLIDO", "Catalán", ""
'
'' ==== BLOQUE 2 — APELLIDOS CATALANES 51–100 ====
'
'AgregarEntradaDiccionario "CA", "ALMIRALL", "ALMIRALL", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "AMAT", "AMAT", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "ARMENGOL", "ARMENGOL", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "ARNAL", "ARNAL", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "ARNÓ", "ARNO", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "ARQUÉ", "ARQUE", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "AUBERT", "AUBERT", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "AUGUET", "AUGUET", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "AVINYÓ", "AVIÑO", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "BADIA", "BADIA", "APELLIDO", "Catalán", ""
'
'AgregarEntradaDiccionario "CA", "BALLESTER", "BALLESTER", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "BALLESTEROS", "BALLESTEROS", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "BARBERÀ", "BARBERA", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "BARTRÉS", "BARTRES", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "BARTOMEU", "BARTOMEU", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "BATALLA", "BATALLA", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "BATLLE", "BATLLE", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "BENET", "BENET", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "BERENGUER", "BERENGUER", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "BERNAT", "BERNAT", "APELLIDO", "Catalán", ""
'
'AgregarEntradaDiccionario "CA", "BESORA", "BESORA", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "BLANCH", "BLANK", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "BLANQUER", "BLANQUER", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "BOADA", "BOADA", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "BOIX", "BOISH", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "BOIXADERA", "BOISHADERA", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "BOIXET", "BOISHET", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "BONET", "BONET", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "BORRÀS", "BORRAS", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "BRUGUERA", "BRUGUERA", "APELLIDO", "Catalán", ""
'
'AgregarEntradaDiccionario "CA", "BRUGUÉS", "BRUGUES", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "BRUNET", "BRUNET", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "BUSQUETS", "BUSQUETS", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "CABALLER", "CABALLER", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "CABALLÉ", "CABALLE", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "CABRÉ", "CABRE", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "CADENAS", "CADENAS", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "CALDERS", "CALDERS", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "CALVET", "CALVET", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "CAMPS", "CAMPS", "APELLIDO", "Catalán", ""
'
'AgregarEntradaDiccionario "CA", "CANALS", "CANALS", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "CANET", "CANET", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "CAPDEVILA", "CAPDEVILA", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "CARBONELL", "CARBONELL", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "CARDELLACH", "CARDELLAK", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "CARRERAS", "CARRERAS", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "CASADEMONT", "CASADEMONT", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "CASANOVAS", "CASANOVAS", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "CASAS", "CASAS", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "CASASSAS", "CASASSAS", "APELLIDO", "Catalán", ""
'
'' ==== BLOQUE 3 — APELLIDOS CATALANES 101–150 ====
'
'AgregarEntradaDiccionario "CA", "CASULLERAS", "CASULLERAS", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "CATALÀ", "CATALA", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "CERVERA", "CERVERA", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "CLARÀ", "CLARA", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "CLARAMUNT", "CLARAMUNT", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "CLARÓS", "CLAROS", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "COLOMER", "COLOMER", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "COMELLAS", "COMELLAS", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "CORBERA", "CORBERA", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "COROMINES", "COROMINES", "APELLIDO", "Catalán", ""
'
'AgregarEntradaDiccionario "CA", "CORTÈS", "CORTES", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "COSTA", "COSTA", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "COTS", "COTS", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "CREUS", "CREUS", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "CROS", "CROS", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "CUGAT", "CUGAT", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "CUNILL", "CUNILL", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "DAGÀS", "DAGAS", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "DARDER", "DARDER", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "DELGADO", "DELGADO", "APELLIDO", "Catalán", ""
'
'AgregarEntradaDiccionario "CA", "DOMÈNECH", "DOMENEK", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "DOMINGO", "DOMINGO", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "DURAN", "DURAN", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "ESCALA", "ESCALA", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "ESCALAS", "ESCALAS", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "ESCOLÀ", "ESCOLA", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "ESCOLANO", "ESCOLANO", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "ESPINALT", "ESPINALT", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "ESPINÀS", "ESPINAS", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "ESTADELLA", "ESTADELLA", "APELLIDO", "Catalán", ""
'
'AgregarEntradaDiccionario "CA", "ESTANY", "ESTAÑ", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "ESTEVE", "ESTEVE", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "ESTEVEZ", "ESTEVEZ", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "ESTRADA", "ESTRADA", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "FABREGAS", "FABREGAS", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "FALGÀS", "FALGAS", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "FARRÉ", "FARRE", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "FARRÉS", "FARRES", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "FERRAN", "FERRAN", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "FIGUERAS", "FIGUERAS", "APELLIDO", "Catalán", ""
'
'AgregarEntradaDiccionario "CA", "FIGUEROLA", "FIGUEROLA", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "FOLCH", "FOLK", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "FONOLLOSA", "FONOLLOSA", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "FORN", "FORN", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "FORNER", "FORNER", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "FORTUNY", "FORTUÑ", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "FREIXAS", "FREISHAS", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "FREIXANET", "FREISHANET", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "FREIXEDAS", "FREISHEDAS", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "FREIXIÓ", "FREISHO", "APELLIDO", "Catalán", ""
'
'' ==== BLOQUE 4 — APELLIDOS CATALANES 151–200 ====
'
'AgregarEntradaDiccionario "CA", "GILI", "GILI", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "GIMBERNAT", "GIMBERNAT", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "GIMENO", "GIMENO", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "GINESTA", "GINESTA", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "GIRALT", "GIRALT", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "GIRONA", "GIRONA", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "GISPERT", "GISPERT", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "GOMIS", "GOMIS", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "GONZALVO", "GONZALVO", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "GORGORIÓ", "GORGORIO", "APELLIDO", "Catalán", ""
'
'AgregarEntradaDiccionario "CA", "GRAS", "GRAS", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "GRASSET", "GRASSET", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "GRAUPERA", "GRAUPERA", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "GRAUS", "GRAUS", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "GRAUET", "GRAUET", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "GRAUPERA", "GRAUPERA", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "GRAUPERAS", "GRAUPERAS", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "GRAUPERET", "GRAUPERET", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "GRAUPERÓ", "GRAUPERO", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "GRAUPERÓS", "GRAUPEROS", "APELLIDO", "Catalán", ""
'
'AgregarEntradaDiccionario "CA", "GUARDIOLA", "GUARDIOLA", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "GUASCH", "GUASK", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "GUASCHET", "GUASKET", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "GUASCHÓ", "GUASKO", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "GUASCHONS", "GUASKONS", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "GUASCHETES", "GUASKETES", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "GUASCHETAS", "GUASKETAS", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "GUASCHETTI", "GUASKETTI", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "GUASCHETTO", "GUASKETTO", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "GUASCHET", "GUASKET", "APELLIDO", "Catalán", ""
'
'AgregarEntradaDiccionario "CA", "JORDÀ", "JORDA", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "JORDI", "JORDI", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "JORDANA", "JORDANA", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "JORDANES", "JORDANES", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "JORDANELL", "JORDANELL", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "JORDANÓ", "JORDANO", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "JORDANÍ", "JORDANI", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "JORDANET", "JORDANET", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "JORDANETS", "JORDANETS", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "JORDANELLÓ", "JORDANELLO", "APELLIDO", "Catalán", ""
'
'AgregarEntradaDiccionario "CA", "JUFRESA", "JUFRESA", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "JUNQUERA", "JUNQUERA", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "JUNQUERAS", "JUNQUERAS", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "JUNQUERÓ", "JUNQUERO", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "JUNQUERET", "JUNQUERET", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "JUNQUERETS", "JUNQUERETS", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "JUNQUERELL", "JUNQUERELL", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "JUNQUERELLÓ", "JUNQUERELLO", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "JUNQUERELLAS", "JUNQUERELLAS", "APELLIDO", "Catalán", ""
'AgregarEntradaDiccionario "CA", "JUNQUERELLATS", "JUNQUERELLATS", "APELLIDO", "Catalán", ""
'
'
'
'End Sub
